# Python Numpy Tutorial


In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,32,7])

In [3]:
myarr

array([ 2,  3, 32,  7])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr[0]

2

In [6]:
myarr[1:3]

array([ 3, 32])

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[1]

3

In [9]:
myarr[1]=5
myarr

array([ 2,  5, 32,  7])

# Array Creatoin: Conversoin from other Python structures

In [12]:
listarray = np.array([1,2,3,4])

In [14]:
listarray

array([1, 2, 3, 4])

In [23]:
listtwodim = np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
listtwodim

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
listtwodim.shape

(2, 4)

In [36]:
listtwodim.dtype

dtype('int32')

In [32]:
listthreedim = np.array([[[1,2,3],[2,3,4],[4,5,6]]])

In [33]:
listthreedim


array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [34]:
listthreedim.shape

(1, 3, 3)

In [37]:
listthreedim.dtype

dtype('int32')

In [38]:
listthreedim.size

9

In [42]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [43]:
zeros=np.zeros([2,5])

In [44]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
rng=np.arange(10)

In [49]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
lspace=np.linspace(1,50,3)

In [57]:
lspace

array([ 1. , 25.5, 50. ])

In [58]:
lspc=np.linspace(1,4,4)

In [59]:
lspc

array([1., 2., 3., 4.])

In [60]:
lspc.shape

(4,)

In [61]:
lspc.size

4

In [73]:
emp= np.empty((4,2))

In [74]:
emp

array([[8.91645664e-313, 0.00000000e+000],
       [3.62633684e+228, 3.57471086e+161],
       [4.27255707e+180, 2.91237123e+257],
       [4.71294503e+257, 6.80210570e-310]])

In [79]:
emp_like = np.empty_like(lspc)

In [80]:
emp_like

array([1., 2., 3., 4.])

In [99]:
arr=np.arange(13)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

1,13 in reshape because it gives 13 on multiplication. 
So, they should be multipled to be give size of array.
1,13 or 1,13,1 or 1,1,13 or .....

In [110]:
arr.reshape(1,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [111]:
arr.reshape(13,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [109]:
arr.reshape(1,1,13)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [107]:
arr.reshape(1,13,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [116]:
x=[[1,2,3],[1,2,4]]

In [117]:
x


[[1, 2, 3], [1, 2, 4]]

In [118]:
ar=np.array(x)

In [119]:
ar

array([[1, 2, 3],
       [1, 2, 4]])

# Axis=0 is vertical and Axis=1 is horizontal

In [120]:
ar.sum()

13

In [122]:
ar.sum(axis=0)

array([2, 4, 7])

In [123]:
ar.sum(axis=1)

array([6, 7])

In [129]:
#######For transposing the array
ar_Trsp=ar.T

In [130]:
ar_Trsp

array([[1, 1],
       [2, 2],
       [3, 4]])

In [131]:
ar_Trsp.sum(axis=0)

array([6, 7])

In [132]:
ar_Trsp.sum(axis=1)

array([2, 4, 7])

In [133]:
#To show the dimension
ar.ndim

2

In [135]:
ar.nbytes

24

In [138]:
ar

array([[1, 2, 3],
       [1, 2, 4]])

In [139]:
#gives the index where the value is minimum
ar.argmin()

0

In [140]:
#gives the index where the value is minimum
ar.argmax()

5

In [143]:
ar[0,1]

2

In [146]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
np.arange(10).argmin()

0

In [148]:
np.arange(10).argmax()

9

In [152]:
a=np.arange(10)

In [154]:
a[0]=100

In [155]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [156]:
a.argmax()

0

In [157]:
a.argmin()

1

In [162]:
#shows the index of the lowwest to highest elements
a.argsort()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int32)

In [165]:
listthreedim

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [167]:
#ravel() is used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array.
listthreedim.ravel()

array([1, 2, 3, 2, 3, 4, 4, 5, 6])

In [168]:
ls1=[1,2,3]
ls2=[3,2,1]
ls1+ls2

[1, 2, 3, 3, 2, 1]

In [169]:
arr1=np.array([1,2,3])
arr2=np.array([3,2,1])
arr1+arr2

array([4, 4, 4])

In [172]:
np.sqrt(arr1 + arr2)

array([2., 2., 2.])

In [173]:
np.max(arr1)

3

In [174]:
np.sum(arr1)

6

In [176]:
arr1.sum()


6

In [177]:
arr1.max()

3

In [187]:
print(arr1)
#gives the index
np.where(arr1>1)

[1 2 3]


(array([1, 2], dtype=int32),)

In [185]:
arr1**2

array([1, 4, 9], dtype=int32)

In [192]:
arrTwo1=np.array([[1,2,4],[0,2,4]])

In [193]:
arrTwo1

array([[1, 2, 4],
       [0, 2, 4]])

In [203]:
(arrTwo1>3)

array([[False, False,  True],
       [False, False,  True]])

In [206]:
np.where(arrTwo1>3)

(array([0, 1], dtype=int32), array([2, 2], dtype=int32))

In [205]:
arrTwo1[np.where(arrTwo1>3)]

array([4, 4])

# For each true value pull from first, for false pull from second

In [254]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]], [[5, 6], [7, 8]])

#Here, [[True, False], [True, True]]  ----> [[1, 2], [3, 4]] and  [[5, 6], [7, 8]]
#True then from first that is 1,3, and 4 , for false from second that is 6 in that corresponding position

array([[1, 6],
       [3, 4]])

In [255]:
a = np.array([[1, 2, 3], [4, 5, 6]])
  
print(a)
  
print ('Indices of elements <4')
  
b = np.where(a<4)
print(b)
  
print("Elements which are <4")

print(a[b])

[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0], dtype=int32), array([0, 1, 2], dtype=int32))
Elements which are <4
[1 2 3]


In [256]:
arr1


array([1, 2, 3])

In [257]:
arr1<3

array([ True,  True, False])

In [258]:
arrWhere = np.where(arr1<3,[True,True,True],[False,False,False])

In [259]:
arrWhere

array([ True,  True, False])

In [271]:
np.logical_or(arr1 < 2,arr1 > 2)

array([ True, False,  True])

In [272]:
arrWhere = np.where(np.logical_or(arr1 < 2,arr1 > 2),['A','A','A'],[False,False,False])

In [273]:
arrWhere

array(['A', 'False', 'A'], dtype='<U5')

In [274]:
np.logical_and(arr1 < 1,arr1 > 2)

array([False, False, False])

In [275]:
arr1

array([1, 2, 3])

In [276]:
np.count_nonzero(arr1)

3

In [269]:
np.nonzero(arr1)

(array([0, 1, 2], dtype=int32),)

In [277]:
listtwodim

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [283]:
np.nonzero(listtwodim)
#read the result as (0,0),(0,1),(0,2),(0,3),(1,0)...... take each vertices vertical wise

(array([0, 0, 0, 1, 1, 1, 1], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 3], dtype=int32))

In [284]:
listtwodim[0,3]=0

In [285]:
listtwodim

array([[1, 2, 3, 0],
       [5, 6, 7, 8]])

In [286]:
np.nonzero(listtwodim)

(array([0, 0, 0, 1, 1, 1, 1], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 3], dtype=int32))

In [287]:
import sys

In [288]:
py_ar = [0,4,55,2]

In [289]:
py_ar

[0, 4, 55, 2]

In [290]:
np_ar=np.array(py_ar)

In [291]:
np_ar

array([ 0,  4, 55,  2])

In [293]:
print(sys.getsizeof(1) * len(py_ar)) #space by list 
print(np_ar.itemsize * np_ar.size) #space by array

56

16