# Python Numpy Tutorial


In [1]:
import numpy as np

In [2]:
myarr = np.array([2,3,32,7])

In [3]:
myarr

array([ 2,  3, 32,  7])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr[0]

2

In [6]:
myarr[1:3]

array([ 3, 32])

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[1]

3

In [9]:
myarr[1]=5
myarr

array([ 2,  5, 32,  7])

# Array Creatoin: Conversoin from other Python structures

In [12]:
listarray = np.array([1,2,3,4])

In [14]:
listarray

array([1, 2, 3, 4])

In [23]:
listtwodim = np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
listtwodim

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
listtwodim.shape

(2, 4)

In [36]:
listtwodim.dtype

dtype('int32')

In [32]:
listthreedim = np.array([[[1,2,3],[2,3,4],[4,5,6]]])

In [33]:
listthreedim


array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [34]:
listthreedim.shape

(1, 3, 3)

In [37]:
listthreedim.dtype

dtype('int32')

In [38]:
listthreedim.size

9

In [42]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [43]:
zeros=np.zeros([2,5])

In [44]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])